name: PLR Safety Check

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Safety-Test:
    runs-on: ubuntu-latest
    env: ${{ secrets }}

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pcntl
          coverage: none

      # Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Run tests
      - name: Run tests
        run: php artisan test --verbose
